#!/usr/bin/env bash
# Configures an Ubuntu server with specific IP requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Create a new hosts file
cp /etc/hosts ~/hosts.new
# For macOS compatibility, use '' after -i
sed -i '' 's/127.0.0.1.*localhost/127.0.0.2 localhost/g' ~/hosts.new
# Remove any existing facebook.com entries
sed -i '' '/facebook.com/d' ~/hosts.new
# Add new facebook.com entry
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
