#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it's executed on

# Using ip command if available, otherwise fallback to ifconfig
if command -v ip > /dev/null; then
    ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
else
    ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*'
fi
